package com.marwadiuniversity.trustlens.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF0E1C2F)
val md_theme_light_onPrimaryContainer = Color(0xFF77849C)
val md_theme_light_secondary = Color(0xFF00639B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF48AFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF004167)
val md_theme_light_tertiary = Color(0xFF000000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF00210E)
val md_theme_light_onTertiaryContainer = Color(0xFF209657)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF7FAFE)
val md_theme_light_onBackground = Color(0xFF181C1F)
val md_theme_light_surface = Color(0xFFF7FAFE)
val md_theme_light_onSurface = Color(0xFF181C1F)
val md_theme_light_surfaceVariant = Color(0xFFE0E3E7)
val md_theme_light_onSurfaceVariant = Color(0xFF44474C)
val md_theme_light_outline = Color(0xFF75777D)
val md_theme_light_outlineVariant = Color(0xFFC5C6CD)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF1F4F8)
val md_theme_light_surfaceContainer = Color(0xFFEBEEF2)
val md_theme_light_surfaceContainerHigh = Color(0xFFE5E8EC)
val md_theme_light_surfaceContainerHighest = Color(0xFFE0E3E7)

val md_theme_dark_primary = Color(0xFFBAC7E1)
val md_theme_dark_onPrimary = Color(0xFF0E1C2F)
val md_theme_dark_primaryContainer = Color(0xFF1E3E62)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FE)
val md_theme_dark_secondary = Color(0xFF96CBFF)
val md_theme_dark_onSecondary = Color(0xFF003355)
val md_theme_dark_secondaryContainer = Color(0xFF004A76)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE5FF)
val md_theme_dark_tertiary = Color(0xFF6FDC95)
val md_theme_dark_onTertiary = Color(0xFF003816)
val md_theme_dark_tertiaryContainer = Color(0xFF00522B)
val md_theme_dark_onTertiaryContainer = Color(0xFF8BF9AF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B192C)
val md_theme_dark_onBackground = Color(0xFFEEF1F5)
val md_theme_dark_surface = Color(0xFF0B192C)
val md_theme_dark_onSurface = Color(0xFFEEF1F5)
val md_theme_dark_surfaceVariant = Color(0xFF44474C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6CD)
val md_theme_dark_outline = Color(0xFF8F9097)
val md_theme_dark_outlineVariant = Color(0xFF44474C)
val md_theme_dark_surfaceContainerLowest = Color(0xFF07111F)
val md_theme_dark_surfaceContainerLow = Color(0xFF112338)
val md_theme_dark_surfaceContainer = Color(0xFF182D46)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1E3E62)
val md_theme_dark_surfaceContainerHighest = Color(0xFF284E7A)

// Custom semantic status colors
val RiskSafe = Color(0xFF16A34A)
val RiskSafeDark = Color(0xFF22C55E)
val RiskWarning = Color(0xFFF59E0B)
val RiskWarningDark = Color(0xFFFBBF24)
val RiskError = Color(0xFFDC2626)
val RiskErrorDark = Color(0xFFEF4444)
